name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    runs-on: ubuntu-24.04
    name: Sync development with master
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Merge master -> development
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: development
          github_token: ${{ secrets.ACCESS_TOKEN }}
          message: 'Sync development with master'
